const { getPool } = require('../db/db');

async function getAllCompanies() {
  const pool = await getPool();

  const query = `
    SELECT TOP 100
      f010_id,
      f010_razon_social,
      f010_nit,
      f010_ind_estado,
      f010_ind_consolidadora,
      f010_max_per_abiertos,
      f010_ult_per_abierto,
      f010_ult_per_cerrado,
      f010_ult_ano_cerrado,
      f010_numero_periodos,
      f010_ind_dias,
      f010_ind_diferido,
      f010_ind_inflacion,
      f010_ind_dif_cambio,
      f010_ind_dist_costos,
      f010_ind_depreciacion_af,
      f010_ind_consecutivo_af,
      f010_consecutivo_af,
      f010_rowid_contacto,
      f010_id_moneda_local,
      f010_id_moneda_conversion,
      f010_id_plan_cuentas,
      f010_rowid_tercero_contab,
      f010_rowid_ccosto_generico,
      f010_rowid_aux_desc_ventas,
      f010_rowid_aux_desc_compras,
      f010_rowid_aux_aprovecha,
      f010_rowid_aux_dif_compras,
      f010_rowid_aux_gyp,
      f010_rowid_ccosto_desc_ventas,
      f010_rowid_ccosto_desc_compras,
      f010_rowid_ccosto_aprovecha,
      f010_rowid_ccosto_dif_compras,
      f010_rowid_fe_generico,
      f010_max_aprovecha,
      f010_max_dif_compras,
      f010_num_resol_gc,
      f010_fecha_resol_gc,
      f010_num_resol_autorete,
      f010_fecha_resol_autorete,
      f010_ind_cdp,
      f010_id_plan_rubro_ppto,
      f010_id_plan_rubro_ccosto,
      f010_notas,
      f010_ciiu,
      f010_dv_nit,
      f010_ind_dist_cuentas,
      f010_ind_reg_fijos,
      f010_ind_trans_cta_puente_af,
      f010_ind_ppto_oc,
      f010_id_plan_ppto_oc,
      f010_ind_valida_periodo_oc,
      f010_ind_valida_co_oc,
      f010_ind_valida_un_oc,
      f010_nivel_ccosto_oc,
      f010_ind_fecha_periodo,
      f010_path_postscript,
      f010_rowid_aux_dif_compras_nd,
      f010_rowid_ccosto_dif_comp_nd,
      f010_max_dif_compras_nd,
      f010_id_moneda_rx,
      f010_ind_contabiliza_gastos,
      f010_ind_co_gastos,
      f010_ind_un_gastos,
      f010_ind_ccosto_gastos,
      f010_per_ini_rx,
      f010_ind_calc_fecha_vcto,
      f010_rowid_movto_entidad,
      f010_rowid_aux_desc_comp2,
      f010_rowid_ccosto_desc_comp2,
      f010_rowid_aux_ingres_comp2,
      f010_rowid_ccosto_ingres_comp2,
      f010_ind_amort_inst_fn,
      f010_id_concepto_ppago_gastos,
      f010_id_motivo_ppago_gastos_fn,
      f010_rowid_aux_desc_vtas2,
      f010_rowid_ccosto_desc_vtas2,
      f010_vlr_max_otros_ingresos,
      f010_ind_depre_salva_af_1,
      f010_ind_depre_salva_af_2,
      f010_ind_pp_anticipo,
      f010_ind_recalc_salva_af_2,
      f010_ind_ppto_of_rp,
      f010_ind_dif_cambio_rx,
      f010_ind_libro_defecto,
      f010_ind_libro1_visible,
      f010_ind_libro2_visible,
      f010_ind_libro3_visible,
      f010_ind_estado_pago_cxp,
      f010_ind_libro_dsto_fin_pp,
      f010_ind_ret_co_movto,
      f010_cant_anual_uvt_pago_efe,
      f010_ind_imp_co_movto_cmp,
      f010_ind_concil_sin_acum_pos
    FROM t010_mm_companias
    WHERE f010_ind_estado = 1
    ORDER BY f010_id DESC
  `;

  const result = await pool.request().query(query);
  return result.recordset;
}

module.exports = { getAllCompanies };
